//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrator
    {
        public long AdminID { get; set; }

        [Key]
        [DisplayName("管理員帳號")]
        [StringLength(40)]
        public string AdminAccount { get; set; }

        [DisplayName("帳號等級")]
        [StringLength(20)]
        [Required]
        public string AccessLevel { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "請填寫密碼")]
        [DataType(DataType.Password)]
        [MinLength(12, ErrorMessage = "密碼最少12碼")]
        [MaxLength(20, ErrorMessage = "密碼最多20碼")]
        public string AdminPassword { get; set; }
    }
}
