//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comments
    {
        [Key]
        public long CommentID { get; set; }

        [DisplayName("商品編號")]
        [StringLength(20)]
        [RegularExpression("[A-F][0-9]{19}")]
        public string ProductID { get; set; }

        [DisplayName("會員帳號")]
        [StringLength(40)]
        public string MemberAccount { get; set; }

        [DisplayName("評論內容")]
        [StringLength(250)]
        public string Content { get; set; }

        [DisplayName("評分")]
        [StringLength(1)]
        public string Score { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Products Products { get; set; }
    }
}
