//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [Key]
        [DisplayName("訂單編號")]
        [StringLength(15)]
        public string OrderID { get; set; }

        [DisplayName("會員帳號")]
        [StringLength(40)]
        public string MemberAccount { get; set; }

        [DisplayName("總價")]
        public Nullable<decimal> TotalPrice { get; set; }

        [DisplayName("訂單成立日期")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime OrderDate { get; set; }

        [DisplayName("出貨日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime ShipDate { get; set; }

        [DisplayName("收貨人地址")]
        [Required(ErrorMessage = "請填寫收貨人地址")]
        [StringLength(60, ErrorMessage = "收貨人地址最多60個字")]
        public string ShipAddress { get; set; }

        [DisplayName("付款方式")]
        [Required(ErrorMessage = "請選擇付款方式")]
        public byte PayTypesID { get; set; }
    
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual PayTypes PayTypes { get; set; }
    }
}
