//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Comments = new HashSet<Comments>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [Key]
        [DisplayName("商品編號")]
        [StringLength(20)]
        [RegularExpression("[A-F][0-9]{19}")]
        public string ProductID { get; set; }

        [DisplayName("商品名稱")]
        [Required(ErrorMessage = "請輸入商品名稱")]
        [StringLength(40, ErrorMessage = "商品名稱最多40個字")]
        public string ProductName { get; set; }

        [DisplayName("供應商帳號")]
        [StringLength(40)]
        public string SupplierAccount { get; set; }

        [DisplayName("庫存量")]
        [Required(ErrorMessage = "請輸入庫存量")]
        [Range(0, int.MaxValue, ErrorMessage = "庫存量不可小於0")]
        public int UnitsInStock { get; set; }

        [DisplayName("商品單價")]
        [Required(ErrorMessage = "請輸入商品單價")]
        [Range(0, int.MaxValue, ErrorMessage = "單價不可小於0")]
        [DisplayFormat(DataFormatString = "{0:C0}", ApplyFormatInEditMode = true)]
        public decimal UnitPrice { get; set; }

        [DisplayName("商品照片")]
        [MaxLength]
        public string ProductImg { get; set; }

        [HiddenInput(DisplayValue = false)]
        [StringLength(20)]
        public string ImageMimeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
